Cost Factors for Basic Set Equipment Modifiers
richardwilkes/gcs_master_library pull request #191
Opened 2022-11-25 09:59 UTC by dec-00

Added versions of the Basic Set Equipment modifiers that use the Cost Factor system introduced in Low-Tech. I copied over the Note from High-Tech Equipment Modifiers because it's a very good explanation of why to use Cost Factor versions.

2022-11-25 23:06 UTC, Calmquist commented on Library/Basic Set/Basic Set Equipment Modifiers.eqm
> +					"cost": "+18 CF"
Shouldn't this be +19?

2022-11-25 23:07 UTC, Calmquist commented on Library/Basic Set/Basic Set Equipment Modifiers.eqm
> +					"cost": "+1 CF"
Shouldn't this be +2?

2022-11-25 23:07 UTC, Calmquist commented on Library/Basic Set/Basic Set Equipment Modifiers.eqm
> +					"cost": "+48 CF"
Shouldn't this be +49?

2022-11-25 23:08 UTC, Calmquist commented on Library/Basic Set/Basic Set Equipment Modifiers.eqm
> +					"cost": "x19"
Shouldn't this be x20?

2022-11-25 23:09 UTC, Calmquist commented on Library/Basic Set/Basic Set Equipment Modifiers.eqm
> +					"cost": "x2"
Shouldn't this be x3?

2022-11-25 23:09 UTC, Calmquist commented on Library/Basic Set/Basic Set Equipment Modifiers.eqm
> +					"cost": "x49"
Shouldn't this be x50?

2022-11-25 23:10 UTC, Calmquist requested changes
Unless the silver modifiers have changed since my edition, they are off by one.

2022-11-25 23:21 UTC, Calmquist commented
I do like adding cost factors.

2022-11-26 00:43 UTC, dec-00 commented
Ah yes. My bad. In my haste I read them as multiply by x instead of add x to the price. I'll fix that.

2022-11-26 18:07 UTC, Calmquist approved these changes

2022-11-27 17:24 UTC, merged