Update Druid.gct
richardwilkes/gcs_master_library pull request #276
Opened 2024-01-13 21:55 UTC by daliin

DFRPG Druid template was lacking the two special skills, Esoteric Medicine (Druidic) and Herb Lore that appear at the end of the Druid template in DFRPG Adventurers (p. 23).

2024-01-13 22:03 UTC, rinickolous requested changes
Please change the container type of the 2 attribute containers to "Attributes". Other than that, no issues.

2024-01-13 22:08 UTC, daliin commented
Changed the two attribute containers to Attributes. Good catch.

2024-01-13 23:29 UTC, daliin commented
Hmm. Apparently I don't fully understand how pull requests work. I meant for the Eldhud racial template changes to be a separate thing, but they've apparently been lumped into the druid request.

2024-01-14 00:21 UTC, rinickolous requested changes
Thanks for the changes. If you could just remove the container saying "Can purchase up to Fire Resistance 15" from the Eldhuhd template as it's non-standard, then this will be approved. While I understand your intention with the container, we don't have consistency across other files with this at the moment.

2024-01-14 17:23 UTC, daliin commented
> Thanks for the changes. If you could just remove the container saying "Can purchase up to Fire Resistance 15" from the Eldhuhd template as it's non-standard, then this will be approved. While I understand your intention with the container, we don't have consistency across other files with this at the moment.

Makes sense. I removed the container.

2024-01-15 16:51 UTC, rinickolous approved these changes

2024-01-15 16:51 UTC, merged