Historical Folks Skill Sets
richardwilkes/gcs_master_library pull request #330
Opened 2024-12-04 22:21 UTC by derrickthewhite

These skill sets are based on combining the 4e Historical Folks with Skill Sets from Action 4: Specialists. The Core Document is at https://docs.google.com/document/d/19Xhz6bQSziJ1xqUfItE2I7r0wBZrW1gg3xZ0FYh9rlc/edit?tab=t.0 

A lot of people have done work contributing to this. 

I know this is my second Contribution to Homebrew stuff in a short time. I promise this is the last one I have just sitting around. Its just that I finally figured out how to do github pull requests. I'll try to contribute to official material again before I go off and do something like submit a bunch of templates from Gurps: Psi-Wars. Though it looks like the two big missing pieces I wanted to work on (DF Summoners and Action 4) got completed...

2024-12-31 21:50 UTC, dripton commented
I will look at this one soon.

2025-01-14 18:49 UTC, dripton commented
These look great overall.  I found a couple of typos:

Misspelled Architect-Master-Builder

Stray 0-point Mechanic in Clock-Maker

It's Home Brew and obviously a lot of work has obviously gone into this, so I'm not going to nitpick any rules choices.  We just want to catch typos.

2025-01-14 18:52 UTC, dripton requested changes
Please fix typo and look at Clock-Maker, then I'll take another pass for typos and approve.

2025-01-14 18:52 UTC, dripton commented on Library/Home Brew/Historical Folks Skill Sets/Skill Sets/Architech-Master-Builder.gct
Typo in file name.  Architech -> Architect

2025-01-14 18:52 UTC, dripton commented on Library/Home Brew/Historical Folks Skill Sets/Skill Sets/Clock-Maker.gct
> +					"id": "2010a3fd-f029-488d-9a92-035986e4825c",
Not sure what this trait container accomplishes.  Just looks like "Mechanic" for 0 points in the traits column in GCS.

2025-01-16 21:54 UTC, derrickthewhite commented on Library/Home Brew/Historical Folks Skill Sets/Skill Sets/Architech-Master-Builder.gct
fixed

2025-01-16 21:54 UTC, derrickthewhite commented on Library/Home Brew/Historical Folks Skill Sets/Skill Sets/Clock-Maker.gct
> +					"id": "2010a3fd-f029-488d-9a92-035986e4825c",
fixed

2025-01-16 22:24 UTC, dripton approved these changes

2025-01-16 22:24 UTC, merged